### ISSUE TITLE
service "webmin" refers to undefined volume wconfig: invalid compose project

### ISSUE THREAD

**Issue by xstable** [zeebote/webmin-on-container#1]
I got following error-message if I try to run your docker-compose.yml:

service "webmin" refers to undefined volume wconfig: invalid compose project
`docker-compose` process finished with exit code 15

What does this entry (wconfig:/) in docker-compose.yml means: 
```
 volumes:
      - wconfig:/etc/webmin
```

**Comment by xstable** [comment]
It seems there is an additional `volumes` section on 1st level missing: 

```
version: '3.8'
services:
  webmin:
    image: trucv/webmin:latest
    init: true
    volumes:
      - wconfig:/etc/webmin
    restart: always
    ports:
      - 10000:10000
    container_name: webmin
volumes:
    wconfig:
        driver: local
```
